# syntax = docker/dockerfile:1.2
# Enable BuildKit https://docs.docker.com/develop/develop-images/build_enhancements/
# Using multistage docker build
# ref: https://docs.docker.com/develop/develop-images/multistage-build/
# Variable to use across build stages
ARG BUILD_HOME=/usr/app

# temp container to cache gradle
FROM gradle:7.4.2-jdk17-jammy AS cache
# Environment vars
ARG BUILD_HOME
ENV APP_HOME=$BUILD_HOME/bot
WORKDIR $APP_HOME
# Copy gradle settings and config to /app in the image
COPY build.gradle settings.gradle $APP_HOME

# Build gradle - caches dependencies
RUN gradle --no-daemon build || return 0

# Build container
FROM cache AS builder
ARG BUILD_HOME
ENV APP_HOME=$BUILD_HOME/bot
# Set where to pull OSRSBot from - default OSRSB
ENV REPO=smeyerhot
# Set where git should store the OSRSBot project
ENV OSRS_REPO=TestRSB/
# Set where git should store the DaxWalkerOSRSBot project
ENV WALKER_REPO=DaxWalkerOSRSBot/

WORKDIR $APP_HOME

# We need to clone the project and cache the git pull - everytime there's something new pushed
# to master it will pull the latest changes
RUN --mount=type=cache,target=/tmp/git_cache/ \
    git clone -b dev https://github.com/$REPO/OsrsBot.git /tmp/git_cache/$OSRS_REPO; \
    cd /tmp/git_cache/$OSRS_REPO && cp -r ./ $BUILD_HOME/$OSRS_REPO
RUN --mount=type=cache,target=/tmp/git_cache/ \
    git clone -b dev https://github.com/$REPO/DaxWalkerOSRSBot.git /tmp/git_cache/$WALKER_REPO; \
    cd /tmp/git_cache/$WALKER_REPO && cp -r ./ $BUILD_HOME/$WALKER_REPO

# Copy over gradle from the cache and copy the src to build it
COPY --from=cache /root/.gradle /root/.gradle
COPY --from=cache $APP_HOME/build.gradle $APP_HOME/settings.gradle $APP_HOME
COPY src/ src/

RUN gradle --no-daemon clean build

# actual container
# Set base image from Docker image repo
# https://adoptium.net/temurin
FROM eclipse-temurin:17-jdk-jammy

ARG BUILD_HOME
ENV APP_HOME=$BUILD_HOME/bot
# Name of the built OSRSBot jar file
ENV BOT_JAR_FILE OSRSBot.jar

# Installs XDisplay packages so we can actually view the container (and run the bot)
# Caches our apt-get(s) with BuildKit
# Remove the apt list to save space
RUN --mount=type=cache,target=/var/cache/apt apt-get update \
    && apt-get upgrade -y \
    && apt-get install -yqq --no-install-recommends libxext6 libxrender1 libxtst6 libxi6 \
    && rm -rf /var/lib/apt/lists/*
#RUN apt-get update && apt-get install libxext6 libxrender1 libxtst6 libxi6 -y

# Adds the bot jar to the container
COPY --from=builder $APP_HOME/$BOT_JAR_FILE $APP_HOME/$BOT_JAR_FILE
# Adds the scripts to the container (copies source files, if you want the built jar comment this out and uncomment the line below)
#COPY --from=builder $APP_HOME/build/scripts root/.config/OsrsBot/Scripts/Sources
COPY --from=builder $APP_HOME/build/libs /root/.config/OsrsBot/Scripts/Precompiled
# Adds runelite config settings to the container
# COPY /config/.runelite/settings.properties /root/.runelite/settings.properties
# # Adds osrsbot account config to the container
# COPY /config/.config/osrsbot_acct.ini /root/.config/osrsbot_acct.ini

EXPOSE 8080

# Launch in RuneLite mode
#ENTRYPOINT java -debug -ea -jar $APP_HOME/${BOT_JAR_FILE} --runelite --developer-mode
ENTRYPOINT java -debug -jar $APP_HOME/${BOT_JAR_FILE} --bot-runelite --developer-mode